/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirnanda;

/**
 *
 * @author DELL
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        awalCB = new javax.swing.JComboBox<>();
        akhirCB = new javax.swing.JComboBox<>();
        awalTF = new javax.swing.JTextField();
        akhirTF = new javax.swing.JTextField();
        convertButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temp. Converter");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Temperature Converter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        awalCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));

        akhirCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));

        awalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awalTFActionPerformed(evt);
            }
        });

        akhirTF.setEditable(false);
        akhirTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akhirTFActionPerformed(evt);
            }
        });

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(awalCB, 0, 92, Short.MAX_VALUE)
                    .addComponent(akhirCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(akhirTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(awalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(convertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(awalCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(awalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertButton)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akhirTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akhirCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void awalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awalTFActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        String box1 = (String)awalCB.getSelectedItem();
        String box2 = (String)akhirCB.getSelectedItem();
        
        // dari celcius
        if(box1.equals("Celcius") && box2.equals("Fahrenheit")){
            double c = Double.parseDouble(awalTF.getText());
            
            double k = (double)(c * 1.8 + 32);
            
            akhirTF.setText(String.valueOf(k));
        }
        
        if(box1.equals("Celcius") && box2.equals("Kelvin")){
            double c = Double.parseDouble(awalTF.getText());
            
            double f = (double)(c + 273);
            
            akhirTF.setText(String.valueOf(f));
        }
        
        if(box1.equals("Celcius") && box2.equals("Reamur")){
            double c = Double.parseDouble(awalTF.getText());
            
            double r = (double)(0.8 * c);
            
            akhirTF.setText(String.valueOf(r));
        }
       
        if(box1.equals("Celcius") && box2.equals("Celcius")){
            double c = Double.parseDouble(awalTF.getText());
            
            akhirTF.setText(String.valueOf(c));
        }
        
        // dari fahrenheit
        if(box1.equals("Fahrenheit") && box2.equals("Celcius")){
            double f = Double.parseDouble(awalTF.getText());
            
            double c = (double)((f - 32)* 0.56);
            
            akhirTF.setText(String.valueOf(c));
        }
        
        if(box1.equals("Fahrenheit") && box2.equals("Kelvin")){
            double f = Double.parseDouble(awalTF.getText());
            
            double k = (double)((f - 32)* 0.56 + 273);
            
            akhirTF.setText(String.valueOf(k));
        }
        
        if(box1.equals("Fahrenheit") && box2.equals("Reamur")){
            double f = Double.parseDouble(awalTF.getText());
            
            double r = (double)((f - 32) * (0.44));
            
            akhirTF.setText(String.valueOf(r));
        }
        
        if(box1.equals("Fahrenheit") && box2.equals("Fahrenheit")){
            double f = Double.parseDouble(awalTF.getText());
            
            akhirTF.setText(String.valueOf(f));
        }
        
        // dari kelvin 
        if(box1.equals("Kelvin") && box2.equals("Celcius")){
            double k = Double.parseDouble(awalTF.getText());
            
            double c = (double)(k - 273);
            
            akhirTF.setText(String.valueOf(c));
        }
        
        if(box1.equals("Kelvin") && box2.equals("Fahrenheit")){
            double k = Double.parseDouble(awalTF.getText());
            
            double f = (double)((k - 273) * 1.8 +32);
            
            akhirTF.setText(String.valueOf(f));
        }
        
        if(box1.equals("Kelvin") && box2.equals("Reamur")){
            double k = Double.parseDouble(awalTF.getText());
            
            double r = (double)((k - 273) * (0.8));
            
            akhirTF.setText(String.valueOf(r));
        }
        
        if(box1.equals("Kelvin") && box2.equals("Kelvin")){
            double k = Double.parseDouble(awalTF.getText());
            
            akhirTF.setText(String.valueOf(k));
        }

        // dari reamur 
        if(box1.equals("Reamur") && box2.equals("Celcius")){
            double r = Double.parseDouble(awalTF.getText());
            
            double c = (double)(r * (1.2));
            
            akhirTF.setText(String.valueOf(c));
        }
        
        if(box1.equals("Reamur") && box2.equals("Fahrenheit")){
            double r = Double.parseDouble(awalTF.getText());
            
            double f = (double)( (r * (1.8)) +32);
            
            akhirTF.setText(String.valueOf(f));
        }
        
        if(box1.equals("Reamur") && box2.equals("Kelvin")){
            double r = Double.parseDouble(awalTF.getText());
            
            double k = (double)((1.2 * r) + 273);
            
            akhirTF.setText(String.valueOf(k));
        }
        
        if(box1.equals("Reamur") && box2.equals("Reamur")){
            double r= Double.parseDouble(awalTF.getText());
            
            akhirTF.setText(String.valueOf(r));
        }
        
    }//GEN-LAST:event_convertButtonActionPerformed

    private void akhirTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akhirTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akhirTFActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        awalTF.setText("");
        akhirTF.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> akhirCB;
    private javax.swing.JTextField akhirTF;
    private javax.swing.JComboBox<String> awalCB;
    private javax.swing.JTextField awalTF;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
